### ISSUE TITLE
ShipmentSentEvent == Too late if the payment fails

### ISSUE THREAD

**Issue by olejohan** [Motillo/klarna-checkout-nopcommerce#1]
Hi, I have not tried your plugin yet (some failure during install, will notify you later if it fails) but I'm already deep into the code and I see a possible problem that I would like to hear about your experence with (as you have a live site already).

Invoice activation is beeing done when the ShipmentSentEvent is called. If it fails an exception is made with "error activating order". We do have an issue with Klarna Faktura (same activation) in maybe 1 in 1000 orders, making it impossible to activate it. (Too old, credit status changed, etc..). 
I assume no one would send the goods away but when the shipmentsentevent is called it could, in our business, be too late to get the goods back (as it's then on the way to the customer).

I would suggest to make the invoice when the shipment is beeing made, not when the shipment is sent ?

Looking forward to hearing from you

**Comment by mlandalv** [comment]
Hello,

I spoke to a Klarna integration guy yesterday related to this. Once the invoice has been created, Klarna takes the risk for that invoice if you activate it within two weeks. From your point of view, nothing changes related to that invoice within those two weeks.

After the two-week period you can still activate the invoice, but the risk is on you. Apparently they are working on new API calls to extend this period or to allow you to double check that everything still is OK, but those are not available yet.

Perhaps this is different to Klarna Faktura (which I haven't used)? Anyway, we have yet to see a failure related to this.

What do you mean with "when the shipment is being made"?

**Comment by olejohan** [comment]
Hi Martin,
 Thanks for your email. I am aware of their invoicing policy, and what you tell me is exactly what they tell me. Unfortunately it seems they are able to change the status so it cannot be activated, in some situations. Perhaps it's fraud orders - and they actually delete the reservation so you cannot find it or activate it.
  
 I meant that it could be activated when you click the "make shipment" button or listen to that event if that would be possible. Then, you would not be able to generate a new shipment before the money is "captured".
  
  
  
  
 Best regards
 Ole Johan
  
  
  

----------------------------------------

**Comment by mlandalv** [comment]
Hi,

When you say "cannot be activated" do you mean through their merchants interface? If something is marked as fraud I believe they notify the store owner (email with a link to a form to fill out or something like that), and remove the reservation from the merchants interface. I still think it can be activated programmatically though, which could happen if it has been shipped before you've been able to do the manual steps involved. (We haven't had this situation yet so I may be wrong.)

It's also part of their [fraud policy](http://cdn.klarna.com/1.0/shared/content/policy/fraud/sv_se/sweden.pdf) that shipments must be trackable, so the logistics company can stop it if Klarna notifies you about a fraud, and you already have shipped it.

I also think it's part of their terms that activation shouldn't occur until the goods are *shipped*, so I think the used event is correct. Can't find a link for that though.

**Comment by olejohan** [comment]
Hi,
 I have spoken with them again and they confirm to me that you are correct, it should not be possible that a reservation can not be activated in their KCO api. This is only a problem in their previous version. :-)
 (Although, they say it according to their documentation it cannot happend in their previous version but they are aware of that it may happend. This is due to an error in their API, they thrown an exception when they really should just inform us - in their previous version)
  
 Thanks for sharing your code
  
 Best regards
  
  
  

----------------------------------------

**Comment by mlandalv** [comment]
Hi,

Great. I guess that means we can close the first issue :smile:.

I hope you find the plugin useful. If you make improvements, you're welcome to send a pull request.

// Martin
